name: build-linux
on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run:  |
              sudo apt-get install libboost-all-dev
              mkdir bin
              cd bin
              cmake ../.
              make
        name: upload_artifact
      - uses: actions/upload-artifact@v3
        with:
          name: artifact-linux-build
          path: |
                  bin/tests
                  bin/generate_key_file
                  bin/Decryptor
                  bin/Encryptor
          retention-days: 1

  rsa-1024-validation:
    runs-on: ubuntu-latest
    needs: [build-linux]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: actions/download-artifact@v3
        name: Download linux build
        with:
          name: artifact-linux-build
      - run:  |
              chmod u+x tests
              ./tests RSA-1024

  rsa-2048-validation:
    runs-on: ubuntu-latest
    needs: [build-linux]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: actions/download-artifact@v3
        name: Download linux build
        with:
          name: artifact-linux-build
      - run:  |
              chmod u+x tests
              ./tests RSA-2048

  SHA3-512-validation-string:
    runs-on: ubuntu-latest
    needs: [build-linux]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: actions/download-artifact@v3
        name: Download linux build
        with:
          name: artifact-linux-build
      - run:  |
              chmod u+x tests
              ./tests SHA3-512

  SHA3-384-validation-string:
    runs-on: ubuntu-latest
    needs: [build-linux]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: actions/download-artifact@v3
        name: Download linux build
        with:
          name: artifact-linux-build
      - run:  |
              chmod u+x tests
              ./tests SHA3-384


  SHA3-256-validation-string:
    runs-on: ubuntu-latest
    needs: [build-linux]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: actions/download-artifact@v3
        name: Download linux build
        with:
          name: artifact-linux-build
      - run:  |
              chmod u+x tests
              ./tests SHA3-256

  SHA3-224-validation-string:
    runs-on: ubuntu-latest
    needs: [build-linux]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: actions/download-artifact@v3
        name: Download linux build
        with:
          name: artifact-linux-build
      - run:  |
              chmod u+x tests
              ./tests SHA3-224


  SHA3-validation-binary_file:
    runs-on: ubuntu-latest
    needs: [build-linux]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: actions/download-artifact@v3
        name: Download linux build
        with:
          name: artifact-linux-build
      - run:  |
              chmod u+x tests
              ./tests SHA3-224-file CI_tests/data/sample_binary_file.jpg 0x549590ab71195bad902cf70cf458076ad5e79e9e91f36327a514225c
              ./tests SHA3-256-file CI_tests/data/sample_binary_file.jpg 0xfe17ce2254961f83860b457a1687e9f524f2f2d873415fa054684928376358f1
              ./tests SHA3-384-file CI_tests/data/sample_binary_file.jpg 0x1b1d5f3d9fdd7c2221f709ad977687220b6eabdc0d1aed3b26b1e35d6dd329b512d74c1e3e6f21d2d8dd4cfac0539fa4
              ./tests SHA3-512-file CI_tests/data/sample_binary_file.jpg 0xc3aa73efdf9079c9fa1c2b304894946b2ba0500940c526a95dc303e84f223e4f7e9fbe2d2e923ffd2254872af31983fdeaf7c0e956097dabd2044a09d94b632c

  KeyFileHandler:
    runs-on: ubuntu-latest
    needs: [build-linux]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: actions/download-artifact@v3
        name: Download linux build
        with:
          name: artifact-linux-build
      - run:  |
              chmod u+x tests
              ./tests KeyFileHandler

  FileListHandler:
    runs-on: ubuntu-latest
    needs: [build-linux]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: actions/download-artifact@v3
        name: Download linux build
        with:
          name: artifact-linux-build
      - run:  |
              chmod u+x tests
              ./tests FileListHandler-hash-file CI_tests/data/example_filelist.txt temp_hash_file.txt 0x33c90af68c410aa916e09188d0a495d897cc9d12420282242d3aeb372244b4e4
              ./tests FileListHandler-up-to-date CI_tests/data/example_filelist.txt temp_hash_file.txt true
              echo "1234" > CI_tests/data/example_filelist.txt
              ./tests FileListHandler-up-to-date CI_tests/data/example_filelist.txt temp_hash_file.txt false

  KeyEncryptionTool:
    runs-on: ubuntu-latest
    needs: [build-linux]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: actions/download-artifact@v3
        name: Download linux build
        with:
          name: artifact-linux-build
      - run:  |
              chmod u+x tests
              ./tests KeyEncryptionTool


  BinaryEncryptionAndDecryption:
    runs-on: ubuntu-latest
    needs: [build-linux]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: actions/download-artifact@v3
        name: Download linux build
        with:
          name: artifact-linux-build
      - run:  |
              chmod u+x generate_key_file
              mkdir temp_test_output
              ./generate_key_file 1024 temp_test_output/temp_key_file.txt <<< 1234567890
              chmod u+x Encryptor
              ./Encryptor temp_test_output/temp_key_file.txt CI_tests/data/example_filelist.txt temp_test_output/encrypted_file
              chmod u+x Decryptor
              ./Decryptor temp_test_output/encrypted_file temp_test_output/ <<< 1234567890
              chmod u+x tests
              ./tests CompareFileHashes  CI_tests/data/example_filelist.txt   temp_test_output/example_filelist.txt
              ./tests CompareFileHashes  CI_tests/data/sample_binary_file.jpg temp_test_output/sample_binary_file.jpg
