name: build-linux
on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run:  |
              sudo apt-get install libboost-all-dev
              mkdir bin
              cd bin
              cmake ../.
              make
        name: upload_artifact
      - uses: actions/upload-artifact@v3
        with:
          name: artifact-linux-build
          path: bin/tests
          retention-days: 1

  rsa-512-validation:
    runs-on: ubuntu-latest
    needs: [build-linux]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: actions/download-artifact@v3
        name: Download linux build
        with:
          name: artifact-linux-build
      - run:  |
              chmod u+x tests
              ./tests RSA-512
